### ISSUE TITLE
Regenerate images

### ISSUE THREAD

**Issue by dos1** [Jimbly/steam-runtime-docker#1]
Steam Runtime repos got a significant update recently: https://github.com/ValveSoftware/steam-runtime/issues/88#issuecomment-432410337

It would be great if the Docker Hub repos could be regenerated against it.

**Comment by Jimbly** [comment]
Wow, someone other than me uses these?!  Great =).  I'll look into it, should be pretty straightforward, as soon as I remember how all of this works =)

**Comment by dos1** [comment]
Haha, yes, I do :) But not from Windows - they're useful for CI.

**Comment by Jimbly** [comment]
Fair enough ^_^.

Looks like nothing much has changed in their scripts to generate the runtime, just the contents in their repos changed, so regenerating these is going fine, though a bit slowly.

**Comment by Jimbly** [comment]
The base images (jimbly/steamrt-precise-base), which I'm guessing is what you're using (judging from the pull numbers being single digits on everything else) have been updated (old ones tagged as :2017).  I've not finished generating the other images descended from those yet, so haven't been able to test my own builds with them, but you can probably test them now and see if they're doing the right thing for you =)

**Comment by Jimbly** [comment]
All images have been regenerated, seem to be working for building Splody; built executable runs with the current Steam client.

Edit: Pushes are still in progress, will probably take an hour before it's mirrored to docker.io.
